# Generated by Django 5.0.1 on 2024-02-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(blank=True, choices=[('S', '1 km'), ('M', '5 km'), ('L', 'unlimited')], max_length=1)),
                ('food', models.CharField(blank=True, choices=[('N', 'north'), ('E', 'northeast'), ('S', 'south'), ('C', 'central')], max_length=1)),
                ('mood', models.CharField(blank=True, choices=[('N', 'nature'), ('A', 'air conditioner'), ('S', 'street Food')], max_length=1)),
                ('updateDate', models.DateField()),
                ('image', models.ImageField(upload_to='recommends')),
                ('isSelected', models.BooleanField(blank=True)),
                ('recommendUser', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('firstName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('Admin', 'admin'), ('Customer', 'users'), ('ShopOwner', 'shopOwner')], max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
